# Generated by Django 5.0.3 on 2024-03-23 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_book_id'),
        ('rentals', '0003_alter_rental_book'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rental',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterField(
            model_name='rental',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book'),
        ),
    ]
